version: '3.8'

services:
  breads-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID:-}
    container_name: breads-fe
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - LINKPREVIEW_API_KEYS=${LINKPREVIEW_API_KEYS:-}
